controller_list:
  - name: fake_jaka_s5_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
initial:  # Define initial robot poses per group
  - group: jaka_s5
    pose: home